// Regenerate bindings with `dart run ffigen.dart`.
import 'dart:io';

import 'package:ffigen/ffigen.dart';

final config = FfiGenerator(
  headers: Headers(
    entryPoints: [
      Uri.file('third_party/boringssl/include/openssl/crypto.h'),
      Uri.file('third_party/boringssl/include/openssl/rand.h'),
      Uri.file('third_party/boringssl/include/openssl/digest.h'),
      Uri.file('third_party/boringssl/include/openssl/cipher.h'),
      Uri.file('third_party/boringssl/include/openssl/cipher.h'),
      Uri.file('third_party/boringssl/include/openssl/aead.h'),
      Uri.file('third_party/boringssl/include/openssl/rsa.h'),
      Uri.file('third_party/boringssl/include/openssl/bn.h'),
      Uri.file('third_party/boringssl/include/openssl/evp.h'),
    ],
    include: (Uri uri) => uri.path.contains('third_party/boringssl/include'),
    compilerOptions: [
      if (Platform.isMacOS) ...['-isysroot', macSdkPath],
      '-Ithird_party/boringssl/include',
    ],
  ),
  output: Output(
    dartFile: Uri.file('lib/src/bindings.g.dart'),
    style: const NativeExternalBindings(
      assetId: 'package:boringssl_dart/boringssl_dart',
    ),
  ),
  functions: Functions.includeSet({
    'RAND_bytes',
    'EVP_MD_CTX_new',
    'EVP_MD_CTX_free',
    'EVP_DigestInit_ex',
    'EVP_DigestUpdate',
    'EVP_DigestFinal_ex',
    'EVP_sha1',
    'EVP_sha256',
    'EVP_sha384',
    'EVP_sha512',
    // Cipher functions
    'EVP_CIPHER_CTX_new',
    'EVP_CIPHER_CTX_free',
    'EVP_CipherInit_ex',
    'EVP_CipherUpdate',
    'EVP_CipherFinal_ex',
    'EVP_CIPHER_CTX_ctrl',
    'EVP_CIPHER_CTX_set_padding',
    // AES ciphers
    'EVP_aes_128_cbc',
    'EVP_aes_192_cbc',
    'EVP_aes_256_cbc',
    'EVP_aes_128_ctr',
    'EVP_aes_192_ctr',
    'EVP_aes_256_ctr',
    'EVP_aes_128_gcm',
    'EVP_aes_256_gcm',
    // AEAD (GCM)
    'EVP_AEAD_CTX_new',
    'EVP_AEAD_CTX_free',
    'EVP_AEAD_CTX_seal',
    'EVP_AEAD_CTX_open',
    'EVP_aead_aes_128_gcm',
    'EVP_aead_aes_192_gcm',
    'EVP_aead_aes_256_gcm',
    // RSA functions
    'EVP_PKEY_new',
    'EVP_PKEY_free',
    'EVP_PKEY_CTX_new',
    'EVP_PKEY_CTX_free',
    'EVP_PKEY_encrypt_init',
    'EVP_PKEY_encrypt',
    'EVP_PKEY_decrypt_init',
    'EVP_PKEY_decrypt',
    'EVP_PKEY_CTX_set_rsa_padding',
    'EVP_PKEY_CTX_set_rsa_oaep_md',
    'EVP_PKEY_CTX_set0_rsa_oaep_label',
    'EVP_PKEY_assign_RSA',
    'EVP_PKEY_set1_RSA',
    'RSA_new',
    'RSA_free',
    'RSA_generate_key_ex',
    'RSA_check_key',
    'RSAPublicKey_dup',
    'RSAPrivateKey_dup',
    'd2i_RSAPublicKey',
    'd2i_RSAPrivateKey',
    'i2d_RSAPublicKey',
    'd2i_RSA_PUBKEY',
    'i2d_RSA_PUBKEY',
    // BIGNUM functions
    'BN_new',
    'BN_free',
    'BN_set_word',
    'BN_get_word',
    // Mem functions
    'OPENSSL_malloc',
    'OPENSSL_free',
  }),
  typedefs: Typedefs.includeSet({
    'EVP_MD_CTX',
    'EVP_MD',
    'EVP_CIPHER',
    'EVP_CIPHER_CTX',
    'EVP_AEAD',
    'EVP_AEAD_CTX',
    'RSA',
    'BIGNUM',
    'BN_GENCB',
    'EVP_PKEY',
    'EVP_PKEY_CTX',
  }),
);

void main() => config.generate();
