// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:boringssl_dart/boringssl_dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> OPENSSL_malloc(int size);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void OPENSSL_free(ffi.Pointer<ffi.Void> ptr);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>()
external int RAND_bytes(ffi.Pointer<ffi.Uint8> buf, int len);

@ffi.Native<ffi.Pointer<EVP_MD> Function()>()
external ffi.Pointer<EVP_MD> EVP_sha1();

@ffi.Native<ffi.Pointer<EVP_MD> Function()>()
external ffi.Pointer<EVP_MD> EVP_sha256();

@ffi.Native<ffi.Pointer<EVP_MD> Function()>()
external ffi.Pointer<EVP_MD> EVP_sha384();

@ffi.Native<ffi.Pointer<EVP_MD> Function()>()
external ffi.Pointer<EVP_MD> EVP_sha512();

@ffi.Native<ffi.Pointer<EVP_MD_CTX> Function()>()
external ffi.Pointer<EVP_MD_CTX> EVP_MD_CTX_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<EVP_MD_CTX>)>()
external void EVP_MD_CTX_free(ffi.Pointer<EVP_MD_CTX> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_MD_CTX>,
    ffi.Pointer<EVP_MD>,
    ffi.Pointer<engine_st>,
  )
>()
external int EVP_DigestInit_ex(
  ffi.Pointer<EVP_MD_CTX> ctx,
  ffi.Pointer<EVP_MD> type,
  ffi.Pointer<engine_st> engine,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<EVP_MD_CTX>, ffi.Pointer<ffi.Void>, ffi.Size)
>()
external int EVP_DigestUpdate(
  ffi.Pointer<EVP_MD_CTX> ctx,
  ffi.Pointer<ffi.Void> data,
  int len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_MD_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>()
external int EVP_DigestFinal_ex(
  ffi.Pointer<EVP_MD_CTX> ctx,
  ffi.Pointer<ffi.Uint8> md_out,
  ffi.Pointer<ffi.UnsignedInt> out_size,
);

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_128_cbc();

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_128_ctr();

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_256_cbc();

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_256_ctr();

@ffi.Native<ffi.Pointer<EVP_CIPHER_CTX> Function()>()
external ffi.Pointer<EVP_CIPHER_CTX> EVP_CIPHER_CTX_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<EVP_CIPHER_CTX>)>()
external void EVP_CIPHER_CTX_free(ffi.Pointer<EVP_CIPHER_CTX> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_CIPHER_CTX>,
    ffi.Pointer<EVP_CIPHER>,
    ffi.Pointer<engine_st>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int,
  )
>()
external int EVP_CipherInit_ex(
  ffi.Pointer<EVP_CIPHER_CTX> ctx,
  ffi.Pointer<EVP_CIPHER> cipher,
  ffi.Pointer<engine_st> engine,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> iv,
  int enc,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_CIPHER_CTX>,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int EVP_CIPHER_CTX_ctrl(
  ffi.Pointer<EVP_CIPHER_CTX> ctx,
  int command,
  int arg,
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_CIPHER_CTX>, ffi.Int)>()
external int EVP_CIPHER_CTX_set_padding(
  ffi.Pointer<EVP_CIPHER_CTX> ctx,
  int pad,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_CIPHER_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int,
  )
>()
external int EVP_CipherUpdate(
  ffi.Pointer<EVP_CIPHER_CTX> ctx,
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Int> out_len,
  ffi.Pointer<ffi.Uint8> in$,
  int in_len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_CIPHER_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Int>,
  )
>()
external int EVP_CipherFinal_ex(
  ffi.Pointer<EVP_CIPHER_CTX> ctx,
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Int> out_len,
);

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_128_gcm();

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_256_gcm();

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_192_cbc();

@ffi.Native<ffi.Pointer<EVP_CIPHER> Function()>()
external ffi.Pointer<EVP_CIPHER> EVP_aes_192_ctr();

@ffi.Native<ffi.Pointer<EVP_AEAD> Function()>()
external ffi.Pointer<EVP_AEAD> EVP_aead_aes_128_gcm();

@ffi.Native<ffi.Pointer<EVP_AEAD> Function()>()
external ffi.Pointer<EVP_AEAD> EVP_aead_aes_192_gcm();

@ffi.Native<ffi.Pointer<EVP_AEAD> Function()>()
external ffi.Pointer<EVP_AEAD> EVP_aead_aes_256_gcm();

@ffi.Native<
  ffi.Pointer<EVP_AEAD_CTX> Function(
    ffi.Pointer<EVP_AEAD>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Size,
  )
>()
external ffi.Pointer<EVP_AEAD_CTX> EVP_AEAD_CTX_new(
  ffi.Pointer<EVP_AEAD> aead,
  ffi.Pointer<ffi.Uint8> key,
  int key_len,
  int tag_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<EVP_AEAD_CTX>)>()
external void EVP_AEAD_CTX_free(ffi.Pointer<EVP_AEAD_CTX> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_AEAD_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Size>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int EVP_AEAD_CTX_seal(
  ffi.Pointer<EVP_AEAD_CTX> ctx,
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Size> out_len,
  int max_out_len,
  ffi.Pointer<ffi.Uint8> nonce,
  int nonce_len,
  ffi.Pointer<ffi.Uint8> in$,
  int in_len,
  ffi.Pointer<ffi.Uint8> ad,
  int ad_len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_AEAD_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Size>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int EVP_AEAD_CTX_open(
  ffi.Pointer<EVP_AEAD_CTX> ctx,
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Size> out_len,
  int max_out_len,
  ffi.Pointer<ffi.Uint8> nonce,
  int nonce_len,
  ffi.Pointer<ffi.Uint8> in$,
  int in_len,
  ffi.Pointer<ffi.Uint8> ad,
  int ad_len,
);

@ffi.Native<ffi.Pointer<RSA> Function()>()
external ffi.Pointer<RSA> RSA_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<RSA>)>()
external void RSA_free(ffi.Pointer<RSA> rsa);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<RSA>,
    ffi.Int,
    ffi.Pointer<BIGNUM>,
    ffi.Pointer<BN_GENCB>,
  )
>()
external int RSA_generate_key_ex(
  ffi.Pointer<RSA> rsa,
  int bits,
  ffi.Pointer<BIGNUM> e,
  ffi.Pointer<BN_GENCB> cb,
);

@ffi.Native<ffi.Pointer<RSA> Function(ffi.Pointer<RSA>)>()
external ffi.Pointer<RSA> RSAPublicKey_dup(ffi.Pointer<RSA> rsa);

@ffi.Native<ffi.Pointer<RSA> Function(ffi.Pointer<RSA>)>()
external ffi.Pointer<RSA> RSAPrivateKey_dup(ffi.Pointer<RSA> rsa);

@ffi.Native<ffi.Int Function(ffi.Pointer<RSA>)>()
external int RSA_check_key(ffi.Pointer<RSA> rsa);

@ffi.Native<
  ffi.Pointer<RSA> Function(
    ffi.Pointer<ffi.Pointer<RSA>>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Long,
  )
>()
external ffi.Pointer<RSA> d2i_RSAPublicKey(
  ffi.Pointer<ffi.Pointer<RSA>> out,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> inp,
  int len,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<RSA>, ffi.Pointer<ffi.Pointer<ffi.Uint8>>)
>()
external int i2d_RSAPublicKey(
  ffi.Pointer<RSA> in$,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> outp,
);

@ffi.Native<
  ffi.Pointer<RSA> Function(
    ffi.Pointer<ffi.Pointer<RSA>>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Long,
  )
>()
external ffi.Pointer<RSA> d2i_RSAPrivateKey(
  ffi.Pointer<ffi.Pointer<RSA>> out,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> inp,
  int len,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<RSA>, ffi.Pointer<ffi.Pointer<ffi.Uint8>>)
>()
external int i2d_RSAPrivateKey(
  ffi.Pointer<RSA> in$,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> outp,
);

@ffi.Native<ffi.Pointer<BIGNUM> Function()>()
external ffi.Pointer<BIGNUM> BN_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<BIGNUM>)>()
external void BN_free(ffi.Pointer<BIGNUM> bn);

@ffi.Native<ffi.Int Function(ffi.Pointer<BIGNUM>, ffi.Uint64)>()
external int BN_set_word(ffi.Pointer<BIGNUM> bn, int value);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<BIGNUM>)>()
external int BN_get_word(ffi.Pointer<BIGNUM> bn);

@ffi.Native<ffi.Pointer<EVP_PKEY> Function()>()
external ffi.Pointer<EVP_PKEY> EVP_PKEY_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<EVP_PKEY>)>()
external void EVP_PKEY_free(ffi.Pointer<EVP_PKEY> pkey);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_PKEY>, ffi.Pointer<RSA>)>()
external int EVP_PKEY_set1_RSA(
  ffi.Pointer<EVP_PKEY> pkey,
  ffi.Pointer<RSA> key,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_PKEY>, ffi.Pointer<RSA>)>()
external int EVP_PKEY_assign_RSA(
  ffi.Pointer<EVP_PKEY> pkey,
  ffi.Pointer<RSA> key,
);

@ffi.Native<ffi.Pointer<RSA> Function(ffi.Pointer<EVP_PKEY>)>()
external ffi.Pointer<RSA> EVP_PKEY_get1_RSA(ffi.Pointer<EVP_PKEY> pkey);

@ffi.Native<
  ffi.Pointer<EVP_PKEY_CTX> Function(
    ffi.Pointer<EVP_PKEY>,
    ffi.Pointer<engine_st>,
  )
>()
external ffi.Pointer<EVP_PKEY_CTX> EVP_PKEY_CTX_new(
  ffi.Pointer<EVP_PKEY> pkey,
  ffi.Pointer<engine_st> e,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<EVP_PKEY_CTX>)>()
external void EVP_PKEY_CTX_free(ffi.Pointer<EVP_PKEY_CTX> ctx);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_PKEY_CTX>)>()
external int EVP_PKEY_encrypt_init(ffi.Pointer<EVP_PKEY_CTX> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_PKEY_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int EVP_PKEY_encrypt(
  ffi.Pointer<EVP_PKEY_CTX> ctx,
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Size> out_len,
  ffi.Pointer<ffi.Uint8> in$,
  int in_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_PKEY_CTX>)>()
external int EVP_PKEY_decrypt_init(ffi.Pointer<EVP_PKEY_CTX> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<EVP_PKEY_CTX>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int EVP_PKEY_decrypt(
  ffi.Pointer<EVP_PKEY_CTX> ctx,
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Size> out_len,
  ffi.Pointer<ffi.Uint8> in$,
  int in_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_PKEY_CTX>, ffi.Int)>()
external int EVP_PKEY_CTX_set_rsa_padding(
  ffi.Pointer<EVP_PKEY_CTX> ctx,
  int padding,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<EVP_PKEY_CTX>, ffi.Pointer<EVP_MD>)>()
external int EVP_PKEY_CTX_set_rsa_oaep_md(
  ffi.Pointer<EVP_PKEY_CTX> ctx,
  ffi.Pointer<EVP_MD> md,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<EVP_PKEY_CTX>, ffi.Pointer<ffi.Uint8>, ffi.Size)
>()
external int EVP_PKEY_CTX_set0_rsa_oaep_label(
  ffi.Pointer<EVP_PKEY_CTX> ctx,
  ffi.Pointer<ffi.Uint8> label,
  int label_len,
);

@ffi.Native<
  ffi.Pointer<EVP_PKEY> Function(
    ffi.Int,
    ffi.Pointer<ffi.Pointer<EVP_PKEY>>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Long,
  )
>()
external ffi.Pointer<EVP_PKEY> d2i_PrivateKey(
  int type,
  ffi.Pointer<ffi.Pointer<EVP_PKEY>> out,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> inp,
  int len,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<RSA>, ffi.Pointer<ffi.Pointer<ffi.Uint8>>)
>()
external int i2d_RSA_PUBKEY(
  ffi.Pointer<RSA> rsa,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> outp,
);

@ffi.Native<
  ffi.Pointer<RSA> Function(
    ffi.Pointer<ffi.Pointer<RSA>>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Long,
  )
>()
external ffi.Pointer<RSA> d2i_RSA_PUBKEY(
  ffi.Pointer<ffi.Pointer<RSA>> out,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> inp,
  int len,
);

final class bignum_st extends ffi.Opaque {}

typedef BIGNUM = bignum_st;

final class bn_gencb_st extends ffi.Opaque {}

typedef BN_GENCB = bn_gencb_st;

final class engine_st extends ffi.Opaque {}

final class env_md_ctx_st extends ffi.Opaque {}

typedef EVP_MD_CTX = env_md_ctx_st;

final class env_md_st extends ffi.Opaque {}

typedef EVP_MD = env_md_st;

final class evp_aead_st extends ffi.Opaque {}

typedef EVP_AEAD = evp_aead_st;

final class evp_aead_ctx_st extends ffi.Opaque {}

typedef EVP_AEAD_CTX = evp_aead_ctx_st;

final class evp_cipher_ctx_st extends ffi.Opaque {}

typedef EVP_CIPHER_CTX = evp_cipher_ctx_st;

final class evp_cipher_st extends ffi.Opaque {}

typedef EVP_CIPHER = evp_cipher_st;

final class evp_pkey_ctx_st extends ffi.Opaque {}

typedef EVP_PKEY_CTX = evp_pkey_ctx_st;

final class evp_pkey_st extends ffi.Opaque {}

typedef EVP_PKEY = evp_pkey_st;

final class rsa_st extends ffi.Opaque {}

typedef RSA = rsa_st;
