// Auto-generated by ffigen.dart. Do not edit.
// Mirrors the pinned BoringSSL commit in native/boringssl_commit.txt.

/// The Git commit hash of BoringSSL that this package is built against.
///
/// This is the value pinned in `native/boringssl_commit.txt`, which the build
/// hook uses to fetch and compile BoringSSL. Embedding programs (e.g. a CLI)
/// can read this constant to report or verify which BoringSSL revision backs
/// the crypto implementation.
const String boringsslCommit = 'beddb582d9e8786a07d79f1cf054d4792b3dd81f';
